// NOTE: When you update this list, please also update list in: doc/index.md
// TODO

import {
    Accordion,
    Breadcrumb,
    Button,
    Card,
    Checkbox,
    Container,
    Divider,
    Grid,
    Header,
    Icon,
    Image,
    Input,
    Item,
    Label,
    List,
    Loader,
    Message,
    Modal,
    Portal,
    Progress,
    Radio,
    Segment,
    Sidebar,
    Step,
    Table
} from 'semantic-ui-react';

import {
    Alert,
    ApproveButton,
    CancelButton,
    Checkmark,
    CopyToClipboardButton,
    Confirm,
    DateInput,
    DateRangeInput,
    DataSegment,
    DataTable,
    Dropdown,
    EditableLabel,
    ErrorMessage,
    Form,
    HighlightText,
    KeyIndicator,
    Loading,
    Menu,
    NodesTree,
    Popup,
    PopupConfirm,
    PopupHelp,
    PopupMenu,
    ReadmeModal,
    ResourceVisibility,
    VisibilityField,
    VisibilityIcon
} from 'cloudify-ui-components';

import { Map, TileLayer, Marker, Popup as LeafletPopup } from 'react-leaflet';

import GenericField from './GenericField';

const Leaflet = {
    Map,
    TileLayer,
    Marker,
    Popup: LeafletPopup
};

export {
    Accordion,
    Alert,
    ApproveButton,
    Breadcrumb,
    Button,
    CancelButton,
    Card,
    Checkbox,
    Checkmark,
    Confirm,
    Container,
    CopyToClipboardButton,
    DateInput,
    DateRangeInput,
    DataSegment,
    DataTable,
    Divider,
    Dropdown,
    EditableLabel,
    ErrorMessage,
    Form,
    GenericField,
    Grid,
    Header,
    HighlightText,
    Icon,
    Image,
    Input,
    Item,
    KeyIndicator,
    Label,
    Leaflet,
    List,
    Loader,
    Loading,
    Menu,
    Message,
    Modal,
    NodesTree,
    Popup,
    PopupConfirm,
    PopupHelp,
    PopupMenu,
    Portal,
    Progress,
    Radio,
    ResourceVisibility,
    ReadmeModal,
    Segment,
    Sidebar,
    Step,
    Table,
    VisibilityIcon,
    VisibilityField
};
