/**
 * Created by kinneretzin on 30/08/2016.
 */

export const ADD_PAGE = 'ADD_PAGE';
export const SET_PAGES = 'SET_PAGES';
export const CREATE_DRILLDOWN_PAGE = 'CREATE_DRILLDOWN_PAGE';
export const ADD_WIDGET = 'ADD_WIDGET';

export const SET_CONTEXT_VALUE = 'SET_CONTEXT_VALUE';
export const CLEAR_CONTEXT = 'CLEAR_CONTEXT';
export const RENAME_PAGE = 'RENAME_PAGE';
export const RENAME_WIDGET = 'RENAME_WIDGET';
export const REMOVE_WIDGET = 'REMOVE_WIDGET';
export const MAXIMIZE_WIDGET = 'MAXIMIZE_WIDGET';
export const MINIMIZE_WIDGETS = 'MINIMIZE_WIDGETS';
export const CHANGE_WIDGET_GRID_DATA = 'CHANGE_WIDGET_GRID_DATA';
export const SHOW_WIDGET_CONFIG = 'SHOW_WIDGET_CONFIG';
export const EDIT_WIDGET = 'EDIT_WIDGET';
export const REMOVE_PAGE = 'REMOVE_PAGE';
export const UPDATE_PAGE_DESCRIPTION = 'UPDATE_PAGE_DESCRIPTION';
export const REORDER_PAGE = 'REORDER_PAGE';

export const ADD_DRILLDOWN_PAGE = 'ADD_DRILLDOWN_PAGE';

export const SET_CONFIG_EDIT_MODE = 'SET_CONFIG_EDIT_MODE';

export const REQ_LOGIN = 'REQ_LOGIN';
export const RES_LOGIN = 'RES_LOGIN';
export const ERR_LOGIN = 'ERR_LOGIN';
export const LOGOUT = 'LOGOUT';

export const REQ_TENANTS = 'REQ_TENANTS';
export const RES_TENANTS = 'RES_TENANTS';
export const ERR_TENANTS = 'ERR_TENANTS';

export const SET_MANAGER_STATUS = 'SET_MANAGER_STATUS';
export const SELECT_TENANT = 'SELECT_TENANT';

export const SET_ACTIVE_EXECUTIONS = 'SET_ACTIVE_EXECUTIONS';
export const CANCEL_EXECUTION = 'CANCEL_EXECUTION';

export const SET_CLIENT_CONFIG = 'SET_CLIENT_CONFIG';

export const SET_APP_LOADING = 'SET_APP_LOADING';

export const WIDGET_FETCH_LOADING  = 'WIDGET_FETCH_LOADING';
export const WIDGET_FETCH_ERROR = 'WIDGET_FETCH_ERROR';
export const WIDGET_FETCH_RES = 'WIDGET_FETCH_RES';
export const WIDGET_FETCH_CANCELED = 'WIDGET_FETCH_CANCELED';
export const WIDGET_DATA_CLEAR = 'WIDGET_DATA_CLEAR';

