/**
 * Created by kinneretzin on 30/08/2016.
 */

export const ADD_PAGE = 'ADD_PAGE';
export const SET_PAGES = 'SET_PAGES';
export const CREATE_DRILLDOWN_PAGE = 'CREATE_DRILLDOWN_PAGE';
export const ADD_WIDGET = 'ADD_WIDGET';
export const INSTALL_WIDGET = 'INSTALL_WIDGET';
export const UNINSTALL_WIDGET = 'UNINSTALL_WIDGET';
export const UPDATE_WIDGET = 'UPDATE_WIDGET';
export const STORE_WIDGETS = 'STORE_WIDGETS';

export const STORE_TEMPLATES = 'STORE_TEMPLATES';
export const ADD_TEMPLATE = 'ADD_TEMPLATE';
export const EDIT_TEMPLATE = 'EDIT_TEMPLATE';
export const REMOVE_TEMPLATE = 'REMOVE_TEMPLATE';

export const ADD_TEMPLATE_PAGE = 'ADD_TEMPLATE_PAGE';
export const REMOVE_TEMPLATE_PAGE = 'REMOVE_TEMPLATE_PAGE';

export const TEMPLATE_MANAGEMENT_LOADING = 'TEMPLATE_MANAGEMENT_LOADING';
export const TEMPLATE_MANAGEMENT_FETCH = 'TEMPLATE_MANAGEMENT_FETCH';
export const TEMPLATE_MANAGEMENT_ERROR = 'TEMPLATE_MANAGEMENT_ERROR';
export const TEMPLATE_MANAGEMENT_SELECT = 'TEMPLATE_MANAGEMENT_SELECT';
export const TEMPLATE_MANAGEMENT_CLEAR = 'TEMPLATE_MANAGEMENT_CLEAR';
export const PAGE_MANAGEMENT_SELECT = 'PAGE_MANAGEMENT_SELECT';
export const PAGE_MANAGEMENT_SHOW = 'PAGE_MANAGEMENT_SHOW';
export const PAGE_MANAGEMENT_CHANGE_NAME = 'PAGE_MANAGEMENT_CHANGE_NAME';
export const PAGE_MANAGEMENT_ADD_WIDGET = 'PAGE_MANAGEMENT_ADD_WIDGET';
export const PAGE_MANAGEMENT_REMOVE_WIDGET = 'PAGE_MANAGEMENT_REMOVE_WIDGET';
export const PAGE_MANAGEMENT_CHANGE_WIDGET = 'PAGE_MANAGEMENT_CHANGE_WIDGET';
export const PAGE_MANAGEMENT_EDIT_WIDGET = 'PAGE_MANAGEMENT_EDIT_WIDGET';
export const PAGE_MANAGEMENT_MAXIMIZE_WIDGET = 'PAGE_MANAGEMENT_MAXIMIZE_WIDGET';
export const PAGE_MANAGEMENT_CLEAR = 'PAGE_MANAGEMENT_CLEAR';
export const PAGE_MANAGEMENT_DRILLDOWN_WARN = 'PAGE_MANAGEMENT_DRILLDOWN_WARN';

export const SET_CONTEXT_VALUE = 'SET_CONTEXT_VALUE';
export const CLEAR_CONTEXT = 'CLEAR_CONTEXT';
export const RENAME_PAGE = 'RENAME_PAGE';
export const RENAME_WIDGET = 'RENAME_WIDGET';
export const REMOVE_WIDGET = 'REMOVE_WIDGET';
export const MAXIMIZE_WIDGET = 'MAXIMIZE_WIDGET';
export const MINIMIZE_WIDGETS = 'MINIMIZE_WIDGETS';
export const CHANGE_WIDGET_GRID_DATA = 'CHANGE_WIDGET_GRID_DATA';
export const SHOW_WIDGET_CONFIG = 'SHOW_WIDGET_CONFIG';
export const EDIT_WIDGET = 'EDIT_WIDGET';
export const REMOVE_PAGE = 'REMOVE_PAGE';
export const UPDATE_PAGE_DESCRIPTION = 'UPDATE_PAGE_DESCRIPTION';
export const REORDER_PAGE = 'REORDER_PAGE';
export const STORE_CURRENT_PAGE = 'STORE_CURRENT_PAGE';
export const STORE_RBAC = 'STORE_RBAC';

export const ADD_DRILLDOWN_PAGE = 'ADD_DRILLDOWN_PAGE';

export const SET_CONFIG_EDIT_MODE = 'SET_CONFIG_EDIT_MODE';

export const REQ_LOGIN = 'REQ_LOGIN';
export const RES_LOGIN = 'RES_LOGIN';
export const ERR_LOGIN = 'ERR_LOGIN';
export const LOGOUT = 'LOGOUT';

export const SET_USER_DATA = 'SET_USER_DATA';

export const REQ_TENANTS = 'REQ_TENANTS';
export const RES_TENANTS = 'RES_TENANTS';
export const ERR_TENANTS = 'ERR_TENANTS';

export const SET_MANAGER_STATUS = 'SET_MANAGER_STATUS';
export const SELECT_TENANT = 'SELECT_TENANT';

export const SET_ACTIVE_EXECUTIONS = 'SET_ACTIVE_EXECUTIONS';
export const CANCEL_EXECUTION = 'CANCEL_EXECUTION';

export const SET_CLIENT_CONFIG = 'SET_CLIENT_CONFIG';

export const SET_APP_LOADING = 'SET_APP_LOADING';
export const SET_APP_ERROR = 'SET_APP_ERROR';
export const APP_SIDEBAR_TOOGLE = 'APP_SIDEBAR_TOOGLE';

export const WIDGET_FETCH_LOADING  = 'WIDGET_FETCH_LOADING';
export const WIDGET_FETCH_ERROR = 'WIDGET_FETCH_ERROR';
export const WIDGET_FETCH_RES = 'WIDGET_FETCH_RES';
export const WIDGET_FETCH_CANCELED = 'WIDGET_FETCH_CANCELED';
export const WIDGET_DATA_CLEAR = 'WIDGET_DATA_CLEAR';

export const SET_DRILLDOWN_CONTEXT = 'SET_DRILLDOWN_CONTEXT';
export const POP_DRILLDOWN_CONTEXT = 'POP_DRILLDOWN_CONTEXT';