import type { Action } from 'redux';

export enum ActionType {
    ADD_TAB,
    REMOVE_TAB,
    UPDATE_TAB,
    MOVE_TAB,

    ADD_PAGE,
    ADD_PAGE_GROUP,
    ADD_PAGE_TO_GROUP,
    SET_PAGES,
    CREATE_DRILLDOWN_PAGE,
    ADD_WIDGET,
    ADD_LAYOUT_SECTION,
    REMOVE_LAYOUT_SECTION,
    INSTALL_WIDGET,
    UNINSTALL_WIDGET,
    UPDATE_WIDGET_DEFINITION,
    STORE_WIDGETS,

    STORE_TEMPLATES,
    ADD_TEMPLATE,
    EDIT_TEMPLATE,
    REMOVE_TEMPLATE,

    ADD_TEMPLATE_PAGE,
    REMOVE_TEMPLATE_PAGE,

    REMOVE_TEMPLATE_PAGE_GROUP,
    CREATE_TEMPLATE_PAGE_GROUP,
    UPDATE_TEMPLATE_PAGE_GROUP,

    TEMPLATE_MANAGEMENT_ACTIVE,
    PAGE_MANAGEMENT_DRILLDOWN_WARN,
    PAGE_MANAGEMENT_SET_EDIT_MODE,

    SET_CONTEXT_VALUE,
    CLEAR_CONTEXT,
    RENAME_PAGE_MENU_ITEM,
    CHANGE_PAGE_MENU_ITEM_ICON,
    REMOVE_WIDGET,
    MINIMIZE_WIDGETS,
    MINIMIZE_TAB_WIDGETS,
    UPDATE_WIDGET,
    REMOVE_PAGE_MENU_ITEM,
    CHANGE_PAGE_DESCRIPTION,
    REORDER_PAGE_MENU,
    STORE_CURRENT_PAGE,
    STORE_RBAC,

    ADD_DRILLDOWN_PAGE,

    SET_CONFIG_EDIT_MODE,

    REQ_LOGIN,
    RES_LOGIN,
    ERR_LOGIN,
    LOGOUT,

    SET_USER_DATA,
    SET_IDENTITY_PROVIDERS,

    REQ_TENANTS,
    RES_TENANTS,
    ERR_TENANTS,

    REQ_CLUSTER_STATUS,
    SET_CLUSTER_STATUS,
    ERR_CLUSTER_STATUS,

    SET_MANAGER_VERSION,
    SET_MANAGER_LICENSE,
    SET_LICENSE_REQUIRED,

    SET_MAINTENANCE_STATUS,
    SELECT_TENANT,

    SET_ACTIVE_EXECUTIONS,
    CANCEL_EXECUTION,

    SET_APP_LOADING,
    SET_APP_ERROR,

    WIDGET_FETCH_LOADING,
    WIDGET_FETCH_ERROR,
    WIDGET_FETCH_RES,
    WIDGET_FETCH_CANCELED,
    WIDGET_DATA_CLEAR,

    SET_DRILLDOWN_CONTEXT,
    POP_DRILLDOWN_CONTEXT,

    SET_PLUGIN_UPLOADING,
    UNSET_PLUGIN_UPLOADING,

    SET_FIELD_ERROR,
    CLEAN_FORM_ERRORS
}

export interface PayloadAction<Payload = unknown, Type = ActionType> extends Action<Type> {
    payload: Payload;
}
