export const NO_TENANTS_ERR = 'NO_TENANTS_ERR';
export const UNAUTHORIZED_ERR = 'UNAUTHORIZED_ERR';
export const LICENSE_ERR = 'LICENSE_ERR';
export const NO_PAGES_FOR_TENANT_ERR = 'NO_PAGES_FOR_TENANT_ERR';
