apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: rpmbuild
    image: rpmbuild/centos7
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 3
        memory: 2Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: node
    image: circleci/node:12.16-browsers
    resources:
      requests:
        cpu: 1.5
        memory: 3Gi
        ephemeral-storage: "15Gi"
      limits:
        cpu: 3
        memory: 3Gi
        ephemeral-storage: "15Gi"
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: postgres
    image: postgres:latest
    ports:
      - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: cloudify
    - name: POSTGRES_PASSWORD
      value: cloudify
    - name: POSTGRES_DB
      value: stage
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  nodeSelector:
    instance-type: spot-xlarge