apiVersion: v1
kind: Pod
spec:
  containers:
<<<<<<< HEAD
  - name: rpmbuild
    image: rpmbuild/centos7
    resources:
      requests:
        cpu: 1.5
=======
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: node
    image: circleci/node:12.22.1-browsers
    resources:
      requests:
        cpu: 1.5
        memory: 8Gi
        ephemeral-storage: "15Gi"
      limits:
        cpu: 3
        memory: 8Gi
        ephemeral-storage: "15Gi"
>>>>>>> 1aef98e9... RD-1766 redesign ci workflow stage (#1445)
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
<<<<<<< HEAD
  - name: node
    image: circleci/node:12.16-browsers
    resources:
      requests:
        cpu: 1.5
        ephemeral-storage: "12Gi"
      limits:
        ephemeral-storage: "15Gi"
=======
  - name: rpmbuild
    image: rpmbuild/centos7
    resources:
      requests:
        cpu: 1
        memory: 3Gi
      limits:
        cpu: 1.5
        memory: 3Gi
>>>>>>> 1aef98e9... RD-1766 redesign ci workflow stage (#1445)
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: postgres
    image: postgres:latest
    ports:
      - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: cloudify
    - name: POSTGRES_PASSWORD
      value: cloudify
    - name: POSTGRES_DB
      value: stage
  nodeSelector:
    instance-type: spot-xlarge