apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: pipelines-efs-volume
      persistentVolumeClaim:
        claimName: pipelines-efs
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: node
    image: circleci/node:12.22.1-browsers
    resources:
      requests:
        cpu: 2.5
        memory: 8Gi
        ephemeral-storage: "15Gi"
      limits:
        cpu: 3.5
        memory: 8Gi
        ephemeral-storage: "15Gi"
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    volumeMounts:
      - mountPath: "/mnt/data"
        name: pipelines-efs-volume
  - name: rpmbuild
    image: rpmbuild/centos7
    resources:
      requests:
        cpu: 0.4
        memory: 5Gi
      limits:
        cpu: 2
        memory: 5Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    volumeMounts:
      - mountPath: "/mnt/data"
        name: pipelines-efs-volume
  - name: postgres
    image: postgres:latest
    ports:
      - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: cloudify
    - name: POSTGRES_PASSWORD
      value: cloudify
    - name: POSTGRES_DB
      value: stage
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  - name: cypress
    image: cypress/base:12
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
