apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: pipelines-efs-volume
      persistentVolumeClaim:
        claimName: pipelines-efs
  containers:
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 0.1
        memory: 256Mi
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.3
        memory: 256Mi
  - name: node
    image: cypress/browsers:node16.14.2-slim-chrome103-ff102
    resources:
      requests:
        cpu: 2.5
        memory: 8Gi
        ephemeral-storage: "15Gi"
      limits:
        cpu: 3.5
        memory: 8Gi
        ephemeral-storage: "15Gi"
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    volumeMounts:
      - mountPath: "/mnt/data"
        name: pipelines-efs-volume
  - name: rpmbuild
    image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-rpmbuild
    resources:
      requests:
        cpu: 0.4
        memory: 5Gi
      limits:
        cpu: 2
        memory: 5Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    volumeMounts:
      - mountPath: "/mnt/data"
        name: pipelines-efs-volume
  - name: postgres
    image: postgres:latest
    ports:
      - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: cloudify
    - name: POSTGRES_PASSWORD
      value: cloudify
    - name: POSTGRES_DB
      value: stage
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
