apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:4.3-4
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  - name: rpmbuild
    image: rpmbuild/centos7
    resources:
      requests:
        cpu: 1.5
        memory: 3Gi
      limits:
        cpu: 1.5
        memory: 3Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot
